# 데이터시각화
1. 학과: AI소프트웨어
2. 학번: 2018315006
3. 성명: 정성엽

In [ ]:
# 라이브러리 가져오기
!pip install pywaffle
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import plotly.express as px
from pywaffle import Waffle
from google.colab import drive
drive.mount('/content/drive')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pywaffle
  Downloading pywaffle-1.1.0-py2.py3-none-any.whl (30 kB)
Collecting fontawesomefree (from pywaffle)
  Downloading fontawesomefree-6.4.0-py3-none-any.whl (25.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.2/25.2 MB 37.5 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from pywaffle) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pywaffle) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->pywaffle) (1.16.0)
Installing collected packages: fontawesomefree, pywaffle
Successfully installed fontawesomefree-6.4.0 pywaffle-1.1.0
Mounted at /content/drive

## 데이터 읽기

In [ ]:
# 치안 트랜드
filename = '/content/drive/MyDrive/Colab_Notebooks/데이터 시각화/data/치안 트랜드 데이터.csv'
df_trend = pd.read_csv(filename, encoding='utf-8')
df_trend.head()

     전체범죄  1273581  1494762  1715720  1898495  1757504  1425078  1693692
0      살인      141      893     1652      957      786      719      821
1      강도        1      698     1596      824      679      487      663
2      절도   160161   194868   229273   229303   208877   176536   204905
3  강간강제추행    10353    16197    22028    26290    21436    17881    21869
4      폭력   250389   287272   323499   370636   339252   274372   328086

In [ ]:
# 열 이름 변경
df_trend.columns = ['범죄유형', '범죄예측2022최소값','범죄예측2022평균값','범죄예측2022최대값','범죄발생수2019','범죄발생수2020', '범죄발생수2021', '평균범죄수3년']
df_trend.head()

,범죄유형,범죄예측2022최소값,범죄예측2022평균값,범죄예측2022최대값,범죄발생수2019,범죄발생수2020,범죄발생수2021,평균범죄수3년
0,살인,141,893,1652,957,786,719,821
1,강도,1,698,1596,824,679,487,663
2,절도,160161,194868,229273,229303,208877,176536,204905
3,강간강제추행,10353,16197,22028,26290,21436,17881,21869
4,폭력,250389,287272,323499,370636,339252,274372,328086

In [ ]:
# 신고 빈발지
filename = '/content/drive/MyDrive/Colab_Notebooks/데이터 시각화/data/신고 빈발지 데이터.csv'
df_report = pd.read_csv(filename, encoding='utf-8')
print(df_report.shape) # 전체적인 열 이름 변경을 위해 열 개수를 알아야함.열의 수가 길기 떄문에 shape을 활용하여 알아보자.
df_report.head()

(249, 12)

   2021  강원도  강릉시  5439  1148  280  98  1  1.1  5  1411  2496
0  2021  강원도  고성군   344    57   14   7  0    0  0   110   156
1  2021  강원도  동해시  2000   481   84  21  0    0  0   544   870
2  2021  강원도  삼척시  1064   221   38  23  0    0  0   286   496
3  2021  강원도  속초시  3023   595  176  36  0    1  4   694  1517
4  2021  강원도  양구군   250    81    3   0  0    0  0    84    82

In [ ]:
# 열 이름 변경
df_report.columns = ['신고년도', '시도','시군구','총\n신고수','가정폭력신고수','데이트폭력신고수','성폭력신고수', '몰래카메라\n신고수', '살인\n신고수', '강도\n신고수', '절도\n신고수', '폭력\n신고수']
# 날짜 오름차순 정렬
df_report = df_report.sort_values(by='신고년도')
df_report.head()

,신고년도,시도,시군구,총\n신고수,가정폭력신고수,데이트폭력신고수,성폭력신고수,몰래카메라\n신고수,살인\n신고수,강도\n신고수,절도\n신고수,폭력\n신고수
0,2021,강원도,고성군,344,57,14,7,0,0,0,110,156
157,2021,서울특별시,양천구,31962,8402,1228,658,16,17,5,10305,11347
158,2021,서울특별시,영등포구,20455,3628,553,675,4,25,4,5979,9591
159,2021,서울특별시,용산구,5679,841,272,214,3,2,1,1516,2833
160,2021,서울특별시,은평구,12359,3086,511,318,0,9,5,3743,4687

In [ ]:
# 안전도 고객 만족도
filename = '/content/drive/MyDrive/Colab_Notebooks/데이터 시각화/data/관서별치안뉴스체감안전도고객만족도대조데이터.csv'
df_safety = pd.read_csv(filename, encoding='utf-8')
print(df_safety.shape) # 전체적인 열 이름 변경을 위해 열 개수를 알아야함.열의 수가 길기 떄문에 shape을 활용하여 알아보자.
df_safety.head()

(260, 23)

,2021,강릉경찰서,17,44,65,225,5,8.1,8.4,7.9,...,6.8,6.8.1,6.8.2,6.5,4.2,7.2,83.8,94.2,57.5,78.7
0,2021,강원고성경찰서,18.0,56.0,60.0,372.0,8.0,8.6,8.9,8.6,...,7.8,7.8,7.7,7.6,3.9,8.0,89.1,94.5,75.5,91.3
1,2021,동해경찰서,7.0,26.0,73.0,137.0,1.0,8.1,8.4,8.2,...,7.2,7.2,7.3,6.9,4.0,7.4,85.1,93.1,61.2,89.3
2,2021,삼척경찰서,11.0,17.0,32.0,103.0,2.0,8.5,8.8,8.4,...,7.4,7.4,7.6,7.4,4.0,8.1,85.4,96.1,54.1,83.0
3,2021,속초경찰서(속초시),24.0,76.0,94.0,211.0,2.0,8.5,8.5,8.2,...,7.2,7.2,7.1,6.9,4.1,8.1,82.5,93.4,64.4,87.6
4,2021,양구경찰서,5.0,11.0,8.0,35.0,4.0,8.4,8.7,8.4,...,7.5,7.8,7.7,7.5,4.0,7.8,83.3,96.9,72.9,85.4

In [ ]:
# 열 이름 변경
df_safety.columns = ['연도', '경찰서명', '국내인명피해사건', '국내비인명피해사건', '국내교통사고', '국내비교통사고', '비리사건', '절도폭력범죄\n안전도', '강도살인범죄\n안전도',
                      '여성대상\n범죄\n안전도', '고통사고\n안전도', '기초법질서\n준수\n안전도', '전반적\n안전도', '순찰\n활동 평가', '교통안전활동\n평가', '기초법질서\n단속\n평가',
                      '공동체\n치안\n예방활동 평가', '타국가\n대비\n치안\n안전도', '야간보행\n안전도', '112신고\n고객만족도', '민원처리\n만족도', '수사처리\n만족도', '교통처리\n만족도'] 
# 날짜 오름차순 정렬
df_safety = df_safety.sort_values(by='연도')
df_safety.head()

,연도,경찰서명,국내인명피해사건,국내비인명피해사건,국내교통사고,국내비교통사고,비리사건,절도폭력범죄\n안전도,강도살인범죄\n안전도,여성대상\n범죄\n안전도,...,순찰\n활동 평가,교통안전활동\n평가,기초법질서\n단속\n평가,공동체\n치안\n예방활동 평가,타국가\n대비\n치안\n안전도,야간보행\n안전도,112신고\n고객만족도,민원처리\n만족도,수사처리\n만족도,교통처리\n만족도
0,2021,강원고성경찰서,18.0,56.0,60.0,372.0,8.0,8.6,8.9,8.6,...,7.8,7.8,7.7,7.6,3.9,8.0,89.1,94.5,75.5,91.3
165,2021,서울양천경찰서,972.0,1682.0,288.0,1039.0,455.0,8.7,8.8,8.3,...,7.2,7.1,7.3,6.8,4.3,8.3,88.7,94.2,60.2,77.6
166,2021,서울영등포경찰서,972.0,1682.0,288.0,1039.0,455.0,8.2,8.3,8.1,...,7.3,7.2,7.3,6.8,4.3,7.8,88.4,93.2,56.8,83.8
167,2021,서울용산경찰서,972.0,1682.0,288.0,1039.0,455.0,8.1,8.4,8.0,...,6.8,6.8,6.7,6.3,4.3,7.9,88.3,95.9,58.6,84.4
168,2021,서울서부경찰서,972.0,1682.0,288.0,1039.0,455.0,8.2,8.5,7.9,...,6.9,6.9,6.7,6.3,4.2,7.8,89.7,95.0,62.9,84.5

In [ ]:
# 서울 CCTV 수 (2022)
filename = '/content/drive/MyDrive/Colab_Notebooks/데이터 시각화/data/서울시 자치구 목적별 CCTV 설치 수량_221231기준.csv'
df_CCTV = pd.read_csv(filename, encoding='cp949')
df_CCTV.head()

,구분,총계,방범,어린이\n보호구역,공원·놀이터,쓰레기\n무단투기,시설안전\n·화재예방,교통단속,교통정보\n수집·분석,기타\n다른법령
0,총 계,"91,341","61,972","9,106","7,466","1,461","3,652","7,216",18,450
1,종로구,"1,980","1,604",44,164,0,34,134,0,0
2,중구,"2,584",1680,76,208,62,62,329,0,167
3,용산구,"2,847","2,132",233,166,0,0,316,0,0
4,성동구,"4,047","2,604",621,216,186,0,420,0,0

In [ ]:
print(df_trend.shape)
print(df_trend.info())

(10, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   범죄유형         10 non-null     object
 1   범죄예측2022최소값  10 non-null     int64
 2   범죄예측2022평균값  10 non-null     int64
 3   범죄예측2022최대값  10 non-null     int64
 4   범죄발생수2019    10 non-null     int64
 5   범죄발생수2020    10 non-null     int64
 6   범죄발생수2021    10 non-null     int64
 7   평균범죄수3년      10 non-null     int64
dtypes: int64(7), object(1)
memory usage: 768.0+ bytes
None

In [ ]:
print(df_report.shape)
print(df_report.info())

(249, 12)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 249 entries, 0 to 248
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   신고년도       249 non-null    int64
 1   시도         249 non-null    object
 2   시군구        249 non-null    object
 3   총
신고수      249 non-null    int64
 4   가정폭력신고수    249 non-null    int64
 5   데이트폭력신고수   249 non-null    int64
 6   성폭력신고수     249 non-null    int64
 7   몰래카메라
신고수  249 non-null    int64
 8   살인
신고수     249 non-null    int64
 9   강도
신고수     249 non-null    int64
 10  절도
신고수     249 non-null    int64
 11  폭력
신고수     249 non-null    int64
dtypes: int64(10), object(2)
memory usage: 25.3+ KB
None

In [ ]:
print(df_safety.shape)
print(df_safety.info())

(260, 23)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 260 entries, 0 to 259
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   연도              260 non-null    int64
 1   경찰서명            260 non-null    object
 2   국내인명피해사건        257 non-null    float64
 3   국내비인명피해사건       257 non-null    float64
 4   국내교통사고          257 non-null    float64
 5   국내비교통사고         257 non-null    float64
 6   비리사건            257 non-null    float64
 7   절도폭력범죄
안전도      260 non-null    float64
 8   강도살인범죄
안전도      260 non-null    float64
 9   여성대상
범죄
안전도     260 non-null    float64
 10  고통사고
안전도        260 non-null    float64
 11  기초법질서
준수
안전도    260 non-null    float64
 12  전반적
안전도         260 non-null    float64
 13  순찰
활동 평가        260 non-null    float64
 14  교통안전활동
평가       260 non-null    float64
 15  기초법질서
단속
평가     260 non-null    float64
 16  공동체
치안
예방활동 평가  260 non-null    float64
 17  타국가
대비
치안
안전도   260 non-null    float64
 18  야간보행
안전도        260 non-null    float64
 19  112신고
고객만족도     259 non-null    float64
 20  민원처리
만족도        259 non-null    float64
 21  수사처리
만족도        259 non-null    float64
 22  교통처리
만족도        259 non-null    float64
dtypes: float64(21), int64(1), object(1)
memory usage: 48.8+ KB
None

In [ ]:
print(df_CCTV.shape)
print(df_CCTV.info())

(26, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   구분          26 non-null     object
 1   총계          26 non-null     object
 2   방범          26 non-null     object
 3   어린이
보호구역    26 non-null     object
 4   공원·놀이터      26 non-null     object
 5   쓰레기
무단투기    26 non-null     object
 6   시설안전
·화재예방  26 non-null     object
 7   교통단속        26 non-null     object
 8   교통정보
수집·분석  26 non-null     int64
 9   기타
다른법령     26 non-null     int64
dtypes: int64(2), object(8)
memory usage: 2.2+ KB
None

In [ ]:
# 결측값 개수 확인
df_trend.isnull().sum()

범죄유형           0
범죄예측2022최소값    0
범죄예측2022평균값    0
범죄예측2022최대값    0
범죄발생수2019      0
범죄발생수2020      0
범죄발생수2021      0
평균범죄수3년        0
dtype: int64

In [ ]:
# 결측값 개수 확인
df_report.isnull().sum()

신고년도          0
시도            0
시군구           0
총\n신고수        0
가정폭력신고수       0
데이트폭력신고수      0
성폭력신고수        0
몰래카메라\n신고수    0
살인\n신고수       0
강도\n신고수       0
절도\n신고수       0
폭력\n신고수       0
dtype: int64

In [ ]:
# 결측값 개수 확인
df_safety.isnull().sum()

연도                  0
경찰서명                0
국내인명피해사건            3
국내비인명피해사건           3
국내교통사고              3
국내비교통사고             3
비리사건                3
절도폭력범죄\n안전도         0
강도살인범죄\n안전도         0
여성대상\n범죄\n안전도       0
고통사고\n안전도           0
기초법질서\n준수\n안전도      0
전반적\n안전도            0
순찰\n활동 평가           0
교통안전활동\n평가          0
기초법질서\n단속\n평가       0
공동체\n치안\n예방활동 평가    0
타국가\n대비\n치안\n안전도    0
야간보행\n안전도           0
112신고\n고객만족도        1
민원처리\n만족도           1
수사처리\n만족도           1
교통처리\n만족도           1
dtype: int64

In [ ]:
# 결측값 개수 확인
df_CCTV.isnull().sum()

구분             0
총계             0
방범             0
어린이\n보호구역      0
공원·놀이터         0
쓰레기\n무단투기      0
시설안전\n·화재예방    0
교통단속           0
교통정보\n수집·분석    0
기타\n다른법령       0
dtype: int64

df_safety 결측값 발견

In [ ]:
# 결측값 처리
# '국내인명피해사건', '국내비인명피해사건', '국내교통사고', '비리사건', '112신고\n고객만족도', '민원처리\n만족도', '수사처리\n만족도', '교통처리\n만족도' 컬럼에는 행에 결측값이 존재하여 해당 행들 삭제: df_dropna
df_safety_dropna = df_safety.dropna(subset = ['국내인명피해사건', '국내비인명피해사건', '국내교통사고', '비리사건', '112신고\n고객만족도', '민원처리\n만족도', '수사처리\n만족도', '교통처리\n만족도'])

In [ ]:
print(df_safety_dropna.shape)
print(df_safety_dropna.isnull().sum())

# 260 -> 256 (4개의 행이 drop)

(256, 23)
연도                  0
경찰서명                0
국내인명피해사건            0
국내비인명피해사건           0
국내교통사고              0
국내비교통사고             0
비리사건                0
절도폭력범죄\n안전도         0
강도살인범죄\n안전도         0
여성대상\n범죄\n안전도       0
고통사고\n안전도           0
기초법질서\n준수\n안전도      0
전반적\n안전도            0
순찰\n활동 평가           0
교통안전활동\n평가          0
기초법질서\n단속\n평가       0
공동체\n치안\n예방활동 평가    0
타국가\n대비\n치안\n안전도    0
야간보행\n안전도           0
112신고\n고객만족도        0
민원처리\n만족도           0
수사처리\n만족도           0
교통처리\n만족도           0
dtype: int64

# 그래프 시각화